/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentmanager;

/**
 *
 * @author USER
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {

        initComponents();
        WelcomeUser.setText("Welcome, " + new Login().GetUserName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JLayeredPane();
        WelcomeUser = new javax.swing.JLabel();
        tabbedPaneCustom1 = new raven.tabbed.TabbedPaneCustom();
        AddStudent = new javax.swing.JPanel();
        AddNewId = new javax.swing.JLabel();
        AddNewPass = new javax.swing.JLabel();
        AddNewUser = new javax.swing.JLabel();
        NewId = new javax.swing.JTextField();
        NewUsername = new javax.swing.JTextField();
        NewPassword = new javax.swing.JTextField();
        SubmitNewStudent = new javax.swing.JButton();
        BackToLogin3 = new javax.swing.JButton();
        DeleteStudent = new javax.swing.JPanel();
        DeleteUser = new javax.swing.JLabel();
        DeleteUserId = new javax.swing.JTextField();
        SubmitDeleteUserBtn = new javax.swing.JButton();
        BackToLogin2 = new javax.swing.JButton();
        UpdateStudent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CurrentStudentId = new javax.swing.JTextField();
        UpdatedStudentUser = new javax.swing.JTextField();
        UpdatedStudentPassword = new javax.swing.JTextField();
        SubmitStudentUpdate = new javax.swing.JButton();
        BackToLogin1 = new javax.swing.JButton();
        LogoutUser = new javax.swing.JButton();
        BGImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        WelcomeUser.setText("Welcome,");

        tabbedPaneCustom1.setBackground(new java.awt.Color(255, 255, 255));
        tabbedPaneCustom1.setForeground(new java.awt.Color(255, 51, 153));
        tabbedPaneCustom1.setSelectedColor(new java.awt.Color(255, 0, 204));

        AddNewId.setText("Enter ID:");

        AddNewPass.setText("Enter Password:");

        AddNewUser.setText("Enter Username:");

        NewId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewIdActionPerformed(evt);
            }
        });

        NewUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewUsernameActionPerformed(evt);
            }
        });

        NewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPasswordActionPerformed(evt);
            }
        });

        SubmitNewStudent.setText("Submit");
        SubmitNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitNewStudentActionPerformed(evt);
            }
        });

        BackToLogin3.setText("Back");
        BackToLogin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToLogin3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddStudentLayout = new javax.swing.GroupLayout(AddStudent);
        AddStudent.setLayout(AddStudentLayout);
        AddStudentLayout.setHorizontalGroup(
            AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddStudentLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddStudentLayout.createSequentialGroup()
                        .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(AddStudentLayout.createSequentialGroup()
                                .addComponent(AddNewId)
                                .addGap(68, 68, 68)
                                .addComponent(NewId, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(SubmitNewStudent)
                                .addGroup(AddStudentLayout.createSequentialGroup()
                                    .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(AddNewPass)
                                        .addComponent(AddNewUser))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(NewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddStudentLayout.createSequentialGroup()
                        .addComponent(BackToLogin3)
                        .addContainerGap())))
        );
        AddStudentLayout.setVerticalGroup(
            AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddStudentLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddNewId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddNewUser))
                .addGap(18, 18, 18)
                .addGroup(AddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddNewPass)
                    .addComponent(NewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SubmitNewStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(BackToLogin3)
                .addContainerGap())
        );

        tabbedPaneCustom1.addTab("Add Student", AddStudent);

        DeleteUser.setText("Enter Id:");

        DeleteUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteUserIdActionPerformed(evt);
            }
        });

        SubmitDeleteUserBtn.setText("Submit");
        SubmitDeleteUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitDeleteUserBtnActionPerformed(evt);
            }
        });

        BackToLogin2.setText("Back");
        BackToLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToLogin2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeleteStudentLayout = new javax.swing.GroupLayout(DeleteStudent);
        DeleteStudent.setLayout(DeleteStudentLayout);
        DeleteStudentLayout.setHorizontalGroup(
            DeleteStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteStudentLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(DeleteStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SubmitDeleteUserBtn)
                    .addGroup(DeleteStudentLayout.createSequentialGroup()
                        .addComponent(DeleteUser)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteStudentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackToLogin2)
                .addContainerGap())
        );
        DeleteStudentLayout.setVerticalGroup(
            DeleteStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteStudentLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(DeleteStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteUser)
                    .addComponent(DeleteUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SubmitDeleteUserBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(BackToLogin2)
                .addContainerGap())
        );

        tabbedPaneCustom1.addTab("Delete Student", DeleteStudent);

        jLabel1.setText("Enter Current Id:");

        jLabel2.setText("Enter New Username:");

        jLabel3.setText("Enter New Password:");

        CurrentStudentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentStudentIdActionPerformed(evt);
            }
        });

        SubmitStudentUpdate.setText("Submit");
        SubmitStudentUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitStudentUpdateActionPerformed(evt);
            }
        });

        BackToLogin1.setText("Back");
        BackToLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToLogin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdateStudentLayout = new javax.swing.GroupLayout(UpdateStudent);
        UpdateStudent.setLayout(UpdateStudentLayout);
        UpdateStudentLayout.setHorizontalGroup(
            UpdateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateStudentLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(UpdateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SubmitStudentUpdate)
                    .addGroup(UpdateStudentLayout.createSequentialGroup()
                        .addGroup(UpdateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(UpdateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CurrentStudentId)
                            .addComponent(UpdatedStudentUser, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(UpdatedStudentPassword))))
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateStudentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackToLogin1)
                .addContainerGap())
        );
        UpdateStudentLayout.setVerticalGroup(
            UpdateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateStudentLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(UpdateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurrentStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(UpdateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(UpdatedStudentUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(UpdateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(UpdatedStudentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(SubmitStudentUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(BackToLogin1)
                .addContainerGap())
        );

        tabbedPaneCustom1.addTab("Update Student", UpdateStudent);

        LogoutUser.setText("Logout");
        LogoutUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutUserActionPerformed(evt);
            }
        });

        MainPanel.setLayer(WelcomeUser, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainPanel.setLayer(tabbedPaneCustom1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainPanel.setLayer(LogoutUser, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap(306, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)
                        .addComponent(LogoutUser)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(WelcomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(423, 423, 423))))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(WelcomeUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutUser)
                .addContainerGap())
        );

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 1, 1050, 430));

        BGImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanager/img/background.jpg"))); // NOI18N
        getContentPane().add(BGImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewPasswordActionPerformed

    private void SubmitNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitNewStudentActionPerformed
      
        new AddStudent().AddStudent(NewId.getText(), NewUsername.getText(), NewPassword.getText());
        
     }//GEN-LAST:event_SubmitNewStudentActionPerformed

    private void DeleteUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteUserIdActionPerformed

    private void SubmitDeleteUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitDeleteUserBtnActionPerformed

        new DeleteStudent().DeleteStudent(DeleteUserId.getText());

    }//GEN-LAST:event_SubmitDeleteUserBtnActionPerformed

    private void NewIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewIdActionPerformed

    private void NewUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUsernameActionPerformed

    private void CurrentStudentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentStudentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentStudentIdActionPerformed

    private void SubmitStudentUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitStudentUpdateActionPerformed

        new UpdateStudent().UpdateStudent(CurrentStudentId.getText(), UpdatedStudentUser.getText(), UpdatedStudentPassword.getText());
        
    }//GEN-LAST:event_SubmitStudentUpdateActionPerformed

    private void LogoutUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutUserActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_LogoutUserActionPerformed

    private void BackToLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToLogin1ActionPerformed
        new Login().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BackToLogin1ActionPerformed

    private void BackToLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToLogin2ActionPerformed
        new Login().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BackToLogin2ActionPerformed

    private void BackToLogin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToLogin3ActionPerformed
        new Login().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BackToLogin3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddNewId;
    private javax.swing.JLabel AddNewPass;
    private javax.swing.JLabel AddNewUser;
    private javax.swing.JPanel AddStudent;
    private javax.swing.JLabel BGImage;
    private javax.swing.JButton BackToLogin1;
    private javax.swing.JButton BackToLogin2;
    private javax.swing.JButton BackToLogin3;
    private javax.swing.JTextField CurrentStudentId;
    private javax.swing.JPanel DeleteStudent;
    private javax.swing.JLabel DeleteUser;
    private javax.swing.JTextField DeleteUserId;
    private javax.swing.JButton LogoutUser;
    private javax.swing.JLayeredPane MainPanel;
    private javax.swing.JTextField NewId;
    private javax.swing.JTextField NewPassword;
    private javax.swing.JTextField NewUsername;
    private javax.swing.JButton SubmitDeleteUserBtn;
    private javax.swing.JButton SubmitNewStudent;
    private javax.swing.JButton SubmitStudentUpdate;
    private javax.swing.JPanel UpdateStudent;
    private javax.swing.JTextField UpdatedStudentPassword;
    private javax.swing.JTextField UpdatedStudentUser;
    private javax.swing.JLabel WelcomeUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private raven.tabbed.TabbedPaneCustom tabbedPaneCustom1;
    // End of variables declaration//GEN-END:variables
}
